
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-frontiers-s26-10
owner: ucsb-cs156-s26
repo_name: proj-frontiers-s26-10
pull_requests: [{"author":{"id":"U_kgDOCxyfpw","is_bot":false,"login":"AmitKarthikeyan","name":"Amit Karthikeyan"},"headRefName":"AK_9","number":32,"title":"DownloadsTab: Add a download for formatted teams CSV","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-10/pull/32"},{"author":{"id":"U_kgDOCuipLw","is_bot":false,"login":"yuhangj554","name":"Yuhang Jiang"},"headRefName":"yj-16","number":31,"title":"DeleteRepos: DELETE /api/repos?courseId=xx&prefix=XXX","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-10/pull/31"},{"author":{"id":"MDQ6VXNlcjc5ODcxOTQ2","is_bot":false,"login":"EpicSRN021","name":""},"headRefName":"sn-issue7-staff-course-show-page","number":30,"title":"StaffCourseShowPage: Add staff course detail page","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-10/pull/30"},{"author":{"id":"U_kgDOCxyfpw","is_bot":false,"login":"AmitKarthikeyan","name":"Amit Karthikeyan"},"headRefName":"AK_12","number":22,"title":"DownloadsTab: Add a downloads tab on the InstructorCourseShowPage","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-10/pull/22"}]
