
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-frontiers-s26-10
owner: ucsb-cs156-s26
repo_name: proj-frontiers-s26-10
pull_requests: [{"author":{"id":"U_kgDOCyT_AA","is_bot":false,"login":"alyoon04","name":""},"headRefName":"alexyoon-issue18","number":24,"title":"DefaultBasePermission: Add hideBasePermissionWarning boolean field to Course entity","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-10/pull/24"},{"author":{"id":"MDQ6VXNlcjc5ODcxOTQ2","is_bot":false,"login":"EpicSRN021","name":""},"headRefName":"sn-issue17-student-course-show-page","number":23,"title":"Student courses: link course names to StudentCourseShowPage placeholder","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-10/pull/23"},{"author":{"id":"U_kgDOCxyfpw","is_bot":false,"login":"AmitKarthikeyan","name":"Amit Karthikeyan"},"headRefName":"AK_12","number":22,"title":"DownloadsTab: Add a downloads tab on the InstructorCourseShowPage","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-10/pull/22"},{"author":{"id":"U_kgDOCyT_AA","is_bot":false,"login":"alyoon04","name":""},"headRefName":"alexyoon-epic","number":20,"title":"EPIC: DownloadStaffCSV - Add backend endpoint, frontend button, and CSV help text","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-10/pull/20"}]
